/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.postgresql:postgresql:42.2.14")
    implementation("org.springframework.boot:spring-boot-starter-data-rest:2.3.3.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.3.3.RELEASE")
    implementation("org.liquibase:liquibase-core:3.8.9")
    implementation("org.springframework.boot:spring-boot-starter-web:2.3.3.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.3.3.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.3.3.RELEASE")
    implementation("org.projectlombok:lombok:1.18.12")
    implementation("org.springdoc:springdoc-openapi-ui:1.4.8")
    implementation("org.springdoc:springdoc-openapi-data-rest:1.4.8")
    implementation("org.springframework.boot:spring-boot-configuration-processor:2.3.3.RELEASE")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.3.3.RELEASE")
    testImplementation("io.zonky.test:embedded-database-spring-test:1.5.4")
}

group = "ru.library"
version = "1.0-SNAPSHOT"
description = "home-library"
java.sourceCompatibility = JavaVersion.VERSION_11

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
