///*
// * This file was generated by the Gradle 'init' task.
// */
//
//plugins {
//    id("org.springframework.boot") version "2.3.3.RELEASE"
//    id("io.spring.dependency-management") version "1.0.9.RELEASE"
//    kotlin("jvm") version "1.3.72"
//    kotlin("plugin.spring") version "1.3.72"
//    kotlin("plugin.jpa") version "1.3.72"
//}
//
//allOpen {
//    annotation("javax.persistence.Entity")
//    annotation("javax.persistence.MappedSuperclass")
//    annotation("javax.persistence.Embeddable")
//}
//
//repositories {
//    mavenLocal()
//    maven {
//        url = uri("https://repo.maven.apache.org/maven2/")
//    }
//}
//
//dependencies {
//    implementation("org.postgresql:postgresql:42.2.14")
//    implementation("org.springframework.boot:spring-boot-starter-data-rest:2.3.3.RELEASE")
//    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.3.3.RELEASE")
//    implementation("org.liquibase:liquibase-core:3.8.9")
//    implementation("org.springframework.boot:spring-boot-starter-web:2.3.3.RELEASE")
//    implementation("org.springframework.boot:spring-boot-starter-validation:2.3.3.RELEASE")
//    implementation("org.springframework.boot:spring-boot-starter-actuator:2.3.3.RELEASE")
//    implementation("org.projectlombok:lombok:1.18.12")
//    implementation("org.springdoc:springdoc-openapi-ui:1.4.8")
//    implementation("org.springdoc:springdoc-openapi-data-rest:1.4.8")
//    implementation("org.springframework.boot:spring-boot-configuration-processor:2.3.3.RELEASE")
//    testImplementation("org.springframework.boot:spring-boot-starter-test:2.3.3.RELEASE")
//    testImplementation("io.zonky.test:embedded-database-spring-test:1.5.4")
//}
//
//group = "ru.library"
//version = "1.0-SNAPSHOT"
//description = "home-library"
//java.sourceCompatibility = JavaVersion.VERSION_11
//
//tasks.withType<JavaCompile>() {
//    options.encoding = "UTF-8"
//}

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    val kotlinVersion = "1.3.72"
    id("org.springframework.boot") version "2.3.3.RELEASE"
    id("io.spring.dependency-management") version "1.0.9.RELEASE"
    kotlin("jvm") version kotlinVersion
    kotlin("plugin.spring") version kotlinVersion
    kotlin("plugin.jpa") version kotlinVersion
}

allOpen {
    annotation("javax.persistence.Entity")
    annotation("javax.persistence.MappedSuperclass")
    annotation("javax.persistence.Embeddable")
}

val openapiVersion = "1.4.8"

group = "ru.library"
version = "1.0.0"

java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-data-rest")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-configuration-processor")
    implementation("org.springdoc:springdoc-openapi-ui:$openapiVersion")
    implementation("org.springdoc:springdoc-openapi-data-rest:$openapiVersion")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.liquibase:liquibase-core")

    runtimeOnly("org.postgresql:postgresql")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("io.zonky.test:embedded-database-spring-test")
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "1.8"
    }
}